name: memoir
description: "My Personal Password Manager"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  android_path_provider:
  flutter_launcher_icons:
  file_picker:
  font_awesome_flutter:
  gap:
  path:
  random_password_generator:
  shared_preferences:
  sqflite:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:
  uses-material-design: true

  assets:
    - "assets/"
    - "assets/images/"

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Light.ttf
        - asset: assets/fonts/RobotoMono-LightItalic.ttf
          style: italic
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 500

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/memoir.png"
